### ISSUE TITLE
User popout

### ISSUE THREAD

**Issue by CodingKanin** [NailaBot/Discord-chat-replica#4]
When clicking on user names show the standard user popout

No status indicator
User name/discrim where nick usually is, user ID where normal name usually is, both clickable to copy
No note or protip ofc, and where the roles usually are just show info like total messages in that archive and possibly more in the future, would be pretty empty for now but would look nicer imo.

**Comment by Bowser65** [comment]
Landed in the big update that occurred a few months ago
![image](https://user-images.githubusercontent.com/9999055/83763142-b4edef80-a678-11ea-81a3-889750f5c8c1.png)
